// <auto-generated />
using System;
using CFP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CFP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902003005_criacaoBD")]
    partial class criacaoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CFP.Entities.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salario")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalizadorDespesas")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalizadorSalario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("CFP.Entities.Despesas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDespesa")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdConta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalizadorDespesasMensal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorDespesa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("contaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("contaId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("CFP.Entities.Despesas", b =>
                {
                    b.HasOne("CFP.Entities.Conta", "conta")
                        .WithMany("Despesas")
                        .HasForeignKey("contaId");

                    b.Navigation("conta");
                });

            modelBuilder.Entity("CFP.Entities.Conta", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
